spring.application.name=proyfin
server.port=8081
# === CONEXIÓN A LA NUBE (AIVEN) ===
spring.datasource.url=jdbc:mysql://conexionsql-ejercicio9.a.aivencloud.com:28330/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_l9ky6Uz8vDy6OxuK7I5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === CONFIGURACIÓN DE HIBERNATE ===
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === CONFIGURACIÓN DE CORREO ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=axelariel04858@gmail.com
spring.mail.password=zssqsqxdnejcxajo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true